### PR TITLE
Added new module: HMMER_EnvBioelement_Search

### PR DESCRIPTION
**Pull request by jungbluth**

### CODE REVIEW

**Comment by bio-boris** [comment]
@jungbluth You should add yourself to https://github.com/kbaseapps/kb_hmmer/blob/master/kbase.yml so you can deploy this specific commit once it gets approved and deployed one time. You will also need to increment the version number in that file in order to get it released.

**Comment by bio-boris** [comment]
Also a release notes with a summary of the changes would be helpful.

**Comment by jungbluth** [comment]
Good comments - added the info.

**Comment by jungbluth** [comment]
@dcchivian could you please review this PR when time permits?

**Review by dcchivian — APPROVED** [review]
Looks good.  I think we should register up only to beta and hammer (hah!) on it a bit to test stability and also identify areas where we need to tighten up before release.  For example, I think we need better descriptive names for some of these gene families.  Go ahead and register the module on APPDEV now up to beta.

**Pull request merged**
